# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

#  flutter analyze lib

linter:
  rules:
    avoid_print: true
    always_declare_return_types: true
    #    always_put_control_body_on_new_line: true
    #    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    #     always_use_package_imports: true
    avoid_catching_errors: true
    avoid_catches_without_on_clauses: true
    #     avoid_classes_with_only_static_members: true
    avoid_empty_else: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_field_initializers_in_const_classes: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    cancel_subscriptions: true
    cascade_invocations: true
    close_sinks: true
    collection_methods_unrelated_type: true
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    deprecated_consistency: true
    deprecated_member_use_from_same_package: true
    document_ignores: true
    empty_catches: true
    empty_statements: true
    exhaustive_cases: true
    flutter_style_todos: true
    hash_and_equals: true
    invalid_case_patterns: true
    #     lines_longer_than_80_chars: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    no_self_assignments: true
    null_check_on_nullable_type_parameter: true
    #     omit_local_variable_types: true
    #     omit_obvious_local_variable_types: true
    omit_obvious_property_types: true
    only_throw_errors: true
    overridden_fields: true
    parameter_assignments: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_final_fields: true
    #     prefer_double_quotes: true
    #     prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    #     prefer_final_parameters: true
    prefer_if_null_operators: true
    prefer_is_not_operator: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    provide_deprecation_message: true
    #     public_member_api_docs: true
    recursive_getters: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    #     sort_constructors_first: true
    #     specify_nonobvious_local_variable_types: true
    throw_in_finally: true
    unnecessary_async: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_const: true
    prefer_expression_function_bodies: false
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
